/net/pr2/projects/plgrid/plggman01/HateSpeech

In [1]:
# ============================================================
# FULL CORRECTED PYTORCH CODE
# Low-Resource Indonesian Hate Speech Detection
# ============================================================

import os
import re
import random
import warnings
import numpy as np
import pandas as pd

from collections import Counter
from scipy.sparse import hstack

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.base import BaseEstimator, ClassifierMixin

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
    DataCollatorWithPadding,
)

warnings.filterwarnings("ignore")

# ============================================================
# 1. GLOBALS
# ============================================================

RANDOM_STATE = 42
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

DATA_DIR = "/net/pr2/projects/plgrid/plggman01/HateSpeech"
OUTPUT_DIR = "./paper_outputs_experiment2"
os.makedirs(OUTPUT_DIR, exist_ok=True)

PATH_IDHSD = os.path.join(DATA_DIR, "IDHSD_RIO_unbalanced_713_2017.txt")
PATH_572 = os.path.join(DATA_DIR, "572-hate-speech-dataset.csv")
PATH_RE = os.path.join(DATA_DIR, "re_dataset.csv")
PATH_KAMUSALAY = os.path.join(DATA_DIR, "new_kamusalay.csv")
PATH_ABUSIVE = os.path.join(DATA_DIR, "abusive.csv")

print("Using device:", DEVICE)

# ============================================================
# 2. SEED
# ============================================================

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(RANDOM_STATE)

# ============================================================
# 3. FILE LOADING
# ============================================================

def safe_read_csv(path, sep=",", header="infer"):
    encodings = ["utf-8", "utf-8-sig", "latin1", "cp1252"]
    last_error = None
    for enc in encodings:
        try:
            return pd.read_csv(path, sep=sep, encoding=enc, header=header)
        except Exception as e:
            last_error = e
    raise ValueError(f"Could not read file {path}. Last error: {last_error}")

def normalize_binary_label(value):
    if pd.isna(value):
        return np.nan

    if isinstance(value, str):
        v = value.strip().lower()
        if v in {"hs", "hate", "hate_speech", "1", "true", "yes"}:
            return 1
        if v in {"non_hs", "non-hs", "non hs", "not_hs", "0", "false", "no"}:
            return 0

    if isinstance(value, (int, float, np.integer, np.floating)):
        return int(value)

    return np.nan

def print_dataset_summary(df, name="dataset"):
    print("\n" + "=" * 70)
    print(f"DATASET: {name}")
    print("=" * 70)
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))
    if "label" in df.columns:
        print("Label distribution:", Counter(df["label"].tolist()))

def load_idhsd_dataset(path):
    df = safe_read_csv(path, sep="\t")
    df = df.rename(columns={"Label": "raw_label", "Tweet": "text"})
    df["label"] = df["raw_label"].apply(normalize_binary_label)
    df["source"] = "IDHSD_713"
    df = df[["text", "label", "source"]].dropna().reset_index(drop=True)
    return df

def load_572_dataset(path):
    df = safe_read_csv(path)

    possible_text_cols = ["comment_text", "tweet", "Tweet", "text", "Text"]
    possible_label_cols = ["class", "label", "Label", "HS"]

    text_col = next((c for c in possible_text_cols if c in df.columns), None)
    label_col = next((c for c in possible_label_cols if c in df.columns), None)

    if text_col is None or label_col is None:
        raise ValueError(f"Could not detect text/label columns in {path}")

    df = df.rename(columns={text_col: "text", label_col: "raw_label"})
    df["label"] = df["raw_label"].apply(normalize_binary_label)
    df["source"] = "HS_572"
    df = df[["text", "label", "source"]].dropna().reset_index(drop=True)
    return df

def load_re_dataset(path):
    df = safe_read_csv(path)

    possible_text_cols = ["Tweet", "tweet", "text", "Text"]
    text_col = next((c for c in possible_text_cols if c in df.columns), None)
    if text_col is None:
        raise ValueError(f"No text column found in {path}")

    if "HS" in df.columns:
        label_col = "HS"
    elif "label" in df.columns:
        label_col = "label"
    else:
        raise ValueError(f"No HS/label column found in {path}")

    df = df.rename(columns={text_col: "text", label_col: "raw_label"})
    df["label"] = df["raw_label"].apply(normalize_binary_label)
    df["source"] = "RE_13169"

    keep_cols = ["text", "label", "source"]
    if "Abusive" in df.columns:
        keep_cols.append("Abusive")

    df = df[keep_cols].dropna(subset=["text", "label"]).reset_index(drop=True)
    return df

def merge_datasets(datasets):
    merged = pd.concat(datasets, axis=0, ignore_index=True)
    merged["text"] = merged["text"].astype(str).str.strip()
    merged = merged[merged["text"].str.len() > 0].copy()
    merged = merged.drop_duplicates(subset=["text"]).reset_index(drop=True)
    return merged

# ============================================================
# 4. TEXT NORMALIZATION
# ============================================================

URL_PATTERN = re.compile(r"http\S+|www\S+|https\S+")
MENTION_PATTERN = re.compile(r"@\w+")
HASHTAG_PATTERN = re.compile(r"#(\w+)")
NON_ALNUM_PATTERN = re.compile(r"[^a-zA-Z0-9\s]")
MULTISPACE_PATTERN = re.compile(r"\s+")
REPEAT_CHAR_PATTERN = re.compile(r"(.)\1{2,}")

LAUGHTER_VARIANTS = {
    "wkwk": "tertawa",
    "wkwkwk": "tertawa",
    "wkwwk": "tertawa",
    "haha": "tertawa",
    "hahaha": "tertawa",
    "hehe": "tertawa",
    "xixi": "tertawa",
}

def load_kamusalay_dict(path):
    df = safe_read_csv(path)
    if df.shape[1] < 2:
        raise ValueError("new_kamusalay.csv must have at least 2 columns.")
    col1, col2 = df.columns[:2]
    slang_dict = {}
    for _, row in df.iterrows():
        src = str(row[col1]).strip().lower()
        tgt = str(row[col2]).strip().lower()
        if src and src != "nan":
            slang_dict[src] = tgt
    return slang_dict

def load_abusive_lexicon(path):
    df = safe_read_csv(path)
    first_col = df.columns[0]
    return set(str(x).strip().lower() for x in df[first_col].dropna().tolist())

def reduce_repeated_chars(text):
    return REPEAT_CHAR_PATTERN.sub(r"\1\1", text)

def split_hashtag(match):
    return f" {match.group(1)} "

def normalize_special_tokens(text):
    tokens = text.split()
    out = []
    for tok in tokens:
        tok = LAUGHTER_VARIANTS.get(tok, tok)
        out.append(tok)
    return " ".join(out)

def basic_clean_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = text.replace("\\n", " ")
    text = text.replace("\\/", "/")
    text = reduce_repeated_chars(text)
    text = URL_PATTERN.sub(" ", text)
    text = MENTION_PATTERN.sub(" ", text)
    text = HASHTAG_PATTERN.sub(split_hashtag, text)
    text = NON_ALNUM_PATTERN.sub(" ", text)
    text = MULTISPACE_PATTERN.sub(" ", text).strip()
    return text

def slang_normalize(text, slang_dict):
    tokens = text.split()
    return " ".join([slang_dict.get(tok, tok) for tok in tokens])

def preprocess_text(text, slang_dict=None):
    text = basic_clean_text(text)
    text = normalize_special_tokens(text)
    if slang_dict is not None:
        text = slang_normalize(text, slang_dict)
    text = MULTISPACE_PATTERN.sub(" ", text).strip()
    return text

def prepare_full_dataset():
    slang_dict = load_kamusalay_dict(PATH_KAMUSALAY)
    abusive_words = load_abusive_lexicon(PATH_ABUSIVE)

    ds_idhsd = load_idhsd_dataset(PATH_IDHSD)
    ds_572 = load_572_dataset(PATH_572)
    ds_re = load_re_dataset(PATH_RE)

    print_dataset_summary(ds_idhsd, "IDHSD")
    print_dataset_summary(ds_572, "572 dataset")
    print_dataset_summary(ds_re, "re_dataset")

    data = merge_datasets([ds_idhsd, ds_572, ds_re])
    data["clean_text"] = data["text"].apply(lambda x: preprocess_text(x, slang_dict))
    data = data[data["clean_text"].str.len() > 2].copy()

    data["abusive_count"] = data["clean_text"].apply(
        lambda txt: sum(1 for tok in txt.split() if tok in abusive_words)
    )

    print_dataset_summary(
        data[["clean_text", "label"]].rename(columns={"clean_text": "text"}),
        "Merged final dataset"
    )
    return data

# ============================================================
# 5. SPLITS
# ============================================================

def make_train_val_test_split(data, test_size=0.2, val_size=0.1):
    train_df, test_df = train_test_split(
        data,
        test_size=test_size,
        random_state=RANDOM_STATE,
        stratify=data["label"]
    )

    train_df, val_df = train_test_split(
        train_df,
        test_size=val_size,
        random_state=RANDOM_STATE,
        stratify=train_df["label"]
    )

    return train_df.reset_index(drop=True), val_df.reset_index(drop=True), test_df.reset_index(drop=True)

def make_low_label_split(train_df, labeled_fraction=0.05):
    labeled_df, unlabeled_df = train_test_split(
        train_df,
        train_size=labeled_fraction,
        random_state=RANDOM_STATE,
        stratify=train_df["label"]
    )
    return labeled_df.reset_index(drop=True), unlabeled_df.reset_index(drop=True)

# ============================================================
# 6. CLASSICAL BASELINES
# ============================================================

class TfidfFusionClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, clf_name="logreg", max_word_features=30000, max_char_features=20000):
        self.clf_name = clf_name
        self.max_word_features = max_word_features
        self.max_char_features = max_char_features

        self.word_vectorizer = TfidfVectorizer(
            analyzer="word",
            ngram_range=(1, 2),
            min_df=2,
            max_features=max_word_features,
            sublinear_tf=True
        )
        self.char_vectorizer = TfidfVectorizer(
            analyzer="char_wb",
            ngram_range=(3, 5),
            min_df=2,
            max_features=max_char_features,
            sublinear_tf=True
        )
        self.clf = None
        self.threshold_ = 0.5

    def _build_clf(self):
        if self.clf_name == "svm":
            return LinearSVC(class_weight="balanced", random_state=RANDOM_STATE)
        if self.clf_name == "logreg":
            return LogisticRegression(max_iter=400, class_weight="balanced", random_state=RANDOM_STATE)
        if self.clf_name == "nb":
            return MultinomialNB()
        raise ValueError(f"Unknown clf_name: {self.clf_name}")

    def fit(self, X, y):
        Xw = self.word_vectorizer.fit_transform(X)
        Xc = self.char_vectorizer.fit_transform(X)
        Xf = hstack([Xw, Xc]).tocsr()
        self.clf = self._build_clf()
        self.clf.fit(Xf, y)
        return self

    def _transform(self, X):
        Xw = self.word_vectorizer.transform(X)
        Xc = self.char_vectorizer.transform(X)
        return hstack([Xw, Xc]).tocsr()

    def predict_proba_like(self, X):
        Xf = self._transform(X)
        if hasattr(self.clf, "predict_proba"):
            return self.clf.predict_proba(Xf)[:, 1]
        if hasattr(self.clf, "decision_function"):
            scores = self.clf.decision_function(Xf)
            scores = np.asarray(scores).reshape(-1)
            return 1 / (1 + np.exp(-scores))
        preds = self.clf.predict(Xf)
        return np.asarray(preds).astype(float)

    def predict(self, X):
        probs = self.predict_proba_like(X)
        return (probs >= self.threshold_).astype(int)

    def set_threshold(self, threshold):
        self.threshold_ = threshold
        return self

# ============================================================
# 7. METRICS
# ============================================================

def evaluate_predictions(y_true, y_pred, y_prob=None, model_name="model"):
    result = {
        "model": model_name,
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_f1": f1_score(y_true, y_pred, average="macro"),
        "macro_precision": precision_score(y_true, y_pred, average="macro", zero_division=0),
        "macro_recall": recall_score(y_true, y_pred, average="macro", zero_division=0),
    }
    if y_prob is not None:
        try:
            result["roc_auc"] = roc_auc_score(y_true, y_prob)
        except Exception:
            result["roc_auc"] = np.nan
    else:
        result["roc_auc"] = np.nan
    return result

def tune_threshold_from_probs(y_true, y_prob):
    best_thr = 0.5
    best_score = -1.0
    for thr in np.arange(0.20, 0.81, 0.02):
        pred = (y_prob >= thr).astype(int)
        score = f1_score(y_true, pred, average="macro")
        if score > best_score:
            best_score = score
            best_thr = float(thr)
    return best_thr, best_score

# ============================================================
# 8. DATASET
# ============================================================

class TokenizedTextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.encodings = tokenizer(
            texts,
            truncation=True,
            padding=False,
            max_length=max_length
        )
        self.labels = list(labels)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

def build_weighted_sampler(labels):
    class_counts = Counter(labels)
    weights = {cls: 1.0 / count for cls, count in class_counts.items()}
    sample_weights = [weights[int(lbl)] for lbl in labels]
    return WeightedRandomSampler(
        weights=sample_weights,
        num_samples=len(sample_weights),
        replacement=True
    )

def get_class_weights(labels):
    counts = Counter(labels)
    total = sum(counts.values())
    n_classes = len(counts)
    weights = {}
    for cls, cnt in counts.items():
        weights[int(cls)] = total / (n_classes * cnt)
    ordered = [weights.get(i, 1.0) for i in sorted(weights.keys())]
    return torch.tensor(ordered, dtype=torch.float)

# ============================================================
# 9. CUSTOM TRAINER
# ============================================================

class WeightedTrainer(Trainer):
    def __init__(self, class_weights=None, train_sampler=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights
        self.train_sampler_override = train_sampler

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        if self.class_weights is not None:
            class_weights = self.class_weights.to(logits.device)
            loss_fct = nn.CrossEntropyLoss(weight=class_weights)
        else:
            loss_fct = nn.CrossEntropyLoss()

        num_labels = logits.size(-1)
        loss = loss_fct(logits.view(-1, num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

    def get_train_dataloader(self):
        if self.train_dataset is None:
            raise ValueError("Trainer: training requires a train_dataset.")
        return DataLoader(
            self.train_dataset,
            batch_size=self.args.train_batch_size,
            sampler=self.train_sampler_override if self.train_sampler_override is not None else None,
            collate_fn=self.data_collator,
            num_workers=0,
            pin_memory=True,
        )

def compute_metrics_for_trainer(eval_pred):
    logits, labels = eval_pred
    probs = torch.softmax(torch.tensor(logits), dim=1)[:, 1].numpy()
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro"),
        "macro_precision": precision_score(labels, preds, average="macro", zero_division=0),
        "macro_recall": recall_score(labels, preds, average="macro", zero_division=0),
        "roc_auc": roc_auc_score(labels, probs) if len(np.unique(labels)) > 1 else np.nan,
    }

# ============================================================
# 10. TRANSFORMER TRAINING
# ============================================================

def run_transformer_model_improved(
    model_checkpoint,
    train_df,
    val_df,
    test_df,
    run_name,
    max_length=128,
    epochs=50,
    batch_size=8,
    learning_rate=2e-5,
    seed=42
):
    set_seed(seed)

    tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_checkpoint,
        num_labels=2
    )

    train_dataset = TokenizedTextDataset(
        train_df["clean_text"].tolist(),
        train_df["label"].tolist(),
        tokenizer=tokenizer,
        max_length=max_length
    )
    val_dataset = TokenizedTextDataset(
        val_df["clean_text"].tolist(),
        val_df["label"].tolist(),
        tokenizer=tokenizer,
        max_length=max_length
    )
    test_dataset = TokenizedTextDataset(
        test_df["clean_text"].tolist(),
        test_df["label"].tolist(),
        tokenizer=tokenizer,
        max_length=max_length
    )

    class_weights = get_class_weights(train_df["label"].tolist())
    sampler = build_weighted_sampler(train_df["label"].tolist())
    collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="pt")

    run_output_dir = os.path.join(OUTPUT_DIR, run_name)
    os.makedirs(run_output_dir, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=run_output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        learning_rate=learning_rate,
        weight_decay=0.01,
        warmup_ratio=0.1,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        report_to="none",
        seed=seed,
        fp16=torch.cuda.is_available(),
        dataloader_pin_memory=True,
    )

    trainer = WeightedTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=collator,
        compute_metrics=compute_metrics_for_trainer,
        class_weights=class_weights,
        train_sampler=sampler,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=50)],
    )

    trainer.train()

    val_output = trainer.predict(val_dataset)
    val_logits = val_output.predictions
    val_prob = torch.softmax(torch.tensor(val_logits), dim=1)[:, 1].numpy()
    best_thr, _ = tune_threshold_from_probs(val_df["label"], val_prob)
    val_pred = (val_prob >= best_thr).astype(int)

    test_output = trainer.predict(test_dataset)
    test_logits = test_output.predictions
    test_prob = torch.softmax(torch.tensor(test_logits), dim=1)[:, 1].numpy()
    test_pred = (test_prob >= best_thr).astype(int)

    print("\n" + "=" * 70)
    print(f"RESULTS: {run_name}")
    print("=" * 70)
    print(classification_report(test_df["label"], test_pred, digits=4))
    print("Confusion Matrix:")
    print(confusion_matrix(test_df["label"], test_pred))

    val_result = evaluate_predictions(val_df["label"], val_pred, val_prob, model_name=run_name)
    test_result = evaluate_predictions(test_df["label"], test_pred, test_prob, model_name=run_name)

    val_result.update({"split": "val", "best_threshold": best_thr, "seed": seed})
    test_result.update({"split": "test", "best_threshold": best_thr, "seed": seed})

    return pd.DataFrame([val_result, test_result]), trainer, tokenizer, best_thr

# ============================================================
# 11. SSL SELECTION
# ============================================================

def predict_transformer_probs(trainer, dataset):
    output = trainer.predict(dataset)
    logits = output.predictions
    return torch.softmax(torch.tensor(logits), dim=1)[:, 1].numpy()

def select_balanced_pseudo_labels(
    unlabeled_df,
    prob1,
    prob2,
    round_idx=1,
    base_threshold=0.92,
    threshold_decay=0.05,
    max_add_per_round=2000
):
    current_thr = max(0.70, base_threshold - (round_idx - 1) * threshold_decay)

    pred1 = (prob1 >= 0.5).astype(int)
    pred2 = (prob2 >= 0.5).astype(int)

    agree = pred1 == pred2
    confident = (
        ((prob1 >= current_thr) | (prob1 <= 1 - current_thr)) &
        ((prob2 >= current_thr) | (prob2 <= 1 - current_thr))
    )
    mask = agree & confident

    cand = unlabeled_df.loc[mask].copy()
    if cand.empty:
        return pd.DataFrame(), unlabeled_df.copy(), current_thr

    cand["pseudo_label"] = pred1[mask]
    cand["conf1"] = prob1[mask]
    cand["conf2"] = prob2[mask]
    cand["confidence"] = (cand["conf1"] + cand["conf2"]) / 2.0
    cand["confidence_margin"] = np.abs(cand["confidence"] - 0.5)

    per_class_cap = max_add_per_round // 2

    hs_cand = cand[cand["pseudo_label"] == 1].sort_values("confidence_margin", ascending=False).head(per_class_cap)
    non_cand = cand[cand["pseudo_label"] == 0].sort_values("confidence_margin", ascending=False).head(per_class_cap)

    selected = pd.concat([hs_cand, non_cand], ignore_index=True)

    if len(selected) < max_add_per_round:
        remaining = cand.drop(index=selected.index, errors="ignore").sort_values("confidence_margin", ascending=False)
        extra_needed = max_add_per_round - len(selected)
        selected = pd.concat([selected, remaining.head(extra_needed)], ignore_index=True)

    selected_texts = set(selected["clean_text"].tolist())
    remaining_df = unlabeled_df[~unlabeled_df["clean_text"].isin(selected_texts)].reset_index(drop=True)

    return selected.reset_index(drop=True), remaining_df, current_thr

def run_ssl_transformer_round_improved(
    labeled_df,
    unlabeled_df,
    val_df,
    test_df,
    scenario_name,
    max_rounds=2,
    max_add_per_round=2000,
    seed=42
):
    current_labeled = labeled_df.copy().reset_index(drop=True)
    current_unlabeled = unlabeled_df.copy().reset_index(drop=True)
    frames = []

    for round_idx in range(1, max_rounds + 1):
        round_name = f"{scenario_name}_ssl_round{round_idx}"
        print("\n" + "#" * 70)
        print(f"SSL ROUND: {round_name}")
        print("#" * 70)

        indobert_results, indobert_trainer, indobert_tokenizer, indobert_thr = run_transformer_model_improved(
            model_checkpoint="indobenchmark/indobert-base-p1",
            train_df=current_labeled,
            val_df=val_df,
            test_df=test_df,
            run_name=f"indobert_{round_name}",
            epochs=50,
            batch_size=8,
            learning_rate=2e-5,
            seed=seed
        )

        xlmr_results, xlmr_trainer, xlmr_tokenizer, xlmr_thr = run_transformer_model_improved(
            model_checkpoint="FacebookAI/xlm-roberta-base",
            train_df=current_labeled,
            val_df=val_df,
            test_df=test_df,
            run_name=f"xlmr_{round_name}",
            epochs=50,
            batch_size=8,
            learning_rate=2e-5,
            seed=seed
        )

        frames.extend([indobert_results, xlmr_results])

        pred_dataset_1 = TokenizedTextDataset(
            current_unlabeled["clean_text"].tolist(),
            [0] * len(current_unlabeled),
            tokenizer=indobert_tokenizer,
            max_length=128
        )
        pred_dataset_2 = TokenizedTextDataset(
            current_unlabeled["clean_text"].tolist(),
            [0] * len(current_unlabeled),
            tokenizer=xlmr_tokenizer,
            max_length=128
        )

        prob1 = predict_transformer_probs(indobert_trainer, pred_dataset_1)
        prob2 = predict_transformer_probs(xlmr_trainer, pred_dataset_2)

        pseudo_df, current_unlabeled, used_thr = select_balanced_pseudo_labels(
            current_unlabeled,
            prob1,
            prob2,
            round_idx=round_idx,
            base_threshold=0.92,
            threshold_decay=0.05,
            max_add_per_round=max_add_per_round
        )

        print("Used pseudo-label threshold:", used_thr)
        print("Pseudo-labeled added:", len(pseudo_df))
        print("Remaining unlabeled:", len(current_unlabeled))

        if pseudo_df.empty:
            break

        pseudo_add = pseudo_df.copy()
        if "label" in pseudo_add.columns:
            pseudo_add = pseudo_add.drop(columns=["label"])
        pseudo_add["label"] = pseudo_df["pseudo_label"].astype(int)
        pseudo_add = pseudo_add.reindex(columns=current_labeled.columns)

        current_labeled = pd.concat([current_labeled, pseudo_add], ignore_index=True)
        current_labeled = current_labeled.drop_duplicates(subset=["clean_text"]).reset_index(drop=True)

    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()

# ============================================================
# 12. MAIN PIPELINE
# ============================================================

def run_full_fixed_pipeline():
    data = prepare_full_dataset()
    train_df, val_df, test_df = make_train_val_test_split(data, test_size=0.2, val_size=0.1)

    scenarios = [0.05, 0.10, 0.20]
    all_results = []

    for frac in scenarios:
        scenario_name = f"{int(frac * 100)}pct"
        print("\n" + "=" * 80)
        print(f"LOW-LABEL SCENARIO: {scenario_name}")
        print("=" * 80)

        labeled_df, unlabeled_df = make_low_label_split(train_df, labeled_fraction=frac)

        indobert_results, indobert_trainer, indobert_tokenizer, indobert_thr = run_transformer_model_improved(
            model_checkpoint="indobenchmark/indobert-base-p1",
            train_df=labeled_df,
            val_df=val_df,
            test_df=test_df,
            run_name=f"indobert_{scenario_name}",
            epochs=50,
            batch_size=8,
            learning_rate=2e-5,
            seed=42
        )
        indobert_results["label_fraction"] = frac
        all_results.append(indobert_results)

        ssl_results = run_ssl_transformer_round_improved(
            labeled_df=labeled_df,
            unlabeled_df=unlabeled_df,
            val_df=val_df,
            test_df=test_df,
            scenario_name=scenario_name,
            max_rounds=2,
            max_add_per_round=max(1000, int(len(labeled_df) * 2)),
            seed=42
        )
        if not ssl_results.empty:
            ssl_results["label_fraction"] = frac
            all_results.append(ssl_results)

    final_results = pd.concat(all_results, axis=0, ignore_index=True)
    final_results.to_csv(os.path.join(OUTPUT_DIR, "final_results_fixed.csv"), index=False)

    print("\nTop TEST results by macro-F1:")
    print(
        final_results[final_results["split"] == "test"]
        .sort_values("macro_f1", ascending=False)
        [["label_fraction", "model", "accuracy", "macro_f1", "macro_precision", "macro_recall", "roc_auc", "best_threshold", "seed"]]
        .head(30)
        .to_string(index=False)
    )

    return final_results

# ============================================================
# 13. ENTRY
# ============================================================

if __name__ == "__main__":
    results = run_full_fixed_pipeline()

2026-04-18 14:26:45.854765: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Using device: cuda

======================================================================
DATASET: IDHSD
======================================================================
Shape: (713, 3)
Columns: ['text', 'label', 'source']
Label distribution: Counter({0: 453, 1: 260})

======================================================================
DATASET: 572 dataset
======================================================================
Shape: (572, 3)
Columns: ['text', 'label', 'source']
Label distribution: Counter({1: 286, 0: 286})

======================================================================
DATASET: re_dataset
======================================================================
Shape: (13169, 4)
Columns: ['text', 'label', 'source', 'Abusive']
Label distribution: Counter({0: 7608, 1: 5561})

======================================================================
DATASET: Merged final dataset
======================================================================
Shape: (14184, 2)
Columns: ['text', 'label']
Label distribution: Counter({0: 8251, 1: 5933})

================================================================================
LOW-LABEL SCENARIO: 5pct
================================================================================

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_5pct
======================================================================
              precision    recall  f1-score   support

           0     0.8335    0.8315    0.8325      1650
           1     0.7666    0.7692    0.7679      1187

    accuracy                         0.8054      2837
   macro avg     0.8001    0.8003    0.8002      2837
weighted avg     0.8055    0.8054    0.8055      2837

Confusion Matrix:
[[1372  278]
 [ 274  913]]

######################################################################
SSL ROUND: 5pct_ssl_round1
######################################################################

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_5pct_ssl_round1
======================================================================
              precision    recall  f1-score   support

           0     0.8335    0.8315    0.8325      1650
           1     0.7666    0.7692    0.7679      1187

    accuracy                         0.8054      2837
   macro avg     0.8001    0.8003    0.8002      2837
weighted avg     0.8055    0.8054    0.8055      2837

Confusion Matrix:
[[1372  278]
 [ 274  913]]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: xlmr_5pct_ssl_round1
======================================================================
              precision    recall  f1-score   support

           0     0.7750    0.8455    0.8087      1650
           1     0.7541    0.6588    0.7032      1187

    accuracy                         0.7674      2837
   macro avg     0.7645    0.7521    0.7560      2837
weighted avg     0.7663    0.7674    0.7646      2837

Confusion Matrix:
[[1395  255]
 [ 405  782]]

Used pseudo-label threshold: 0.92
Pseudo-labeled added: 1020
Remaining unlabeled: 8682

######################################################################
SSL ROUND: 5pct_ssl_round2
######################################################################

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_5pct_ssl_round2
======================================================================
              precision    recall  f1-score   support

           0     0.8289    0.8339    0.8314      1650
           1     0.7672    0.7607    0.7640      1187

    accuracy                         0.8033      2837
   macro avg     0.7981    0.7973    0.7977      2837
weighted avg     0.8031    0.8033    0.8032      2837

Confusion Matrix:
[[1376  274]
 [ 284  903]]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: xlmr_5pct_ssl_round2
======================================================================
              precision    recall  f1-score   support

           0     0.8520    0.7782    0.8134      1650
           1     0.7248    0.8121    0.7660      1187

    accuracy                         0.7924      2837
   macro avg     0.7884    0.7952    0.7897      2837
weighted avg     0.7988    0.7924    0.7936      2837

Confusion Matrix:
[[1284  366]
 [ 223  964]]

Used pseudo-label threshold: 0.87
Pseudo-labeled added: 1020
Remaining unlabeled: 7662

================================================================================
LOW-LABEL SCENARIO: 10pct
================================================================================

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_10pct
======================================================================
              precision    recall  f1-score   support

           0     0.8585    0.8461    0.8523      1650
           1     0.7903    0.8062    0.7982      1187

    accuracy                         0.8294      2837
   macro avg     0.8244    0.8261    0.8252      2837
weighted avg     0.8300    0.8294    0.8296      2837

Confusion Matrix:
[[1396  254]
 [ 230  957]]

######################################################################
SSL ROUND: 10pct_ssl_round1
######################################################################

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_10pct_ssl_round1
======================================================================
              precision    recall  f1-score   support

           0     0.8585    0.8461    0.8523      1650
           1     0.7903    0.8062    0.7982      1187

    accuracy                         0.8294      2837
   macro avg     0.8244    0.8261    0.8252      2837
weighted avg     0.8300    0.8294    0.8296      2837

Confusion Matrix:
[[1396  254]
 [ 230  957]]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: xlmr_10pct_ssl_round1
======================================================================
              precision    recall  f1-score   support

           0     0.8318    0.8424    0.8371      1650
           1     0.7770    0.7633    0.7701      1187

    accuracy                         0.8093      2837
   macro avg     0.8044    0.8028    0.8036      2837
weighted avg     0.8089    0.8093    0.8091      2837

Confusion Matrix:
[[1390  260]
 [ 281  906]]

Used pseudo-label threshold: 0.92
Pseudo-labeled added: 2042
Remaining unlabeled: 7149

######################################################################
SSL ROUND: 10pct_ssl_round2
######################################################################

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_10pct_ssl_round2
======================================================================
              precision    recall  f1-score   support

           0     0.8372    0.8727    0.8546      1650
           1     0.8120    0.7641    0.7873      1187

    accuracy                         0.8273      2837
   macro avg     0.8246    0.8184    0.8210      2837
weighted avg     0.8267    0.8273    0.8265      2837

Confusion Matrix:
[[1440  210]
 [ 280  907]]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: xlmr_10pct_ssl_round2
======================================================================
              precision    recall  f1-score   support

           0     0.8363    0.8667    0.8512      1650
           1     0.8048    0.7641    0.7839      1187

    accuracy                         0.8238      2837
   macro avg     0.8205    0.8154    0.8176      2837
weighted avg     0.8231    0.8238    0.8230      2837

Confusion Matrix:
[[1430  220]
 [ 280  907]]

Used pseudo-label threshold: 0.87
Pseudo-labeled added: 2042
Remaining unlabeled: 5107

================================================================================
LOW-LABEL SCENARIO: 20pct
================================================================================

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_20pct
======================================================================
              precision    recall  f1-score   support

           0     0.8607    0.8648    0.8628      1650
           1     0.8109    0.8054    0.8081      1187

    accuracy                         0.8400      2837
   macro avg     0.8358    0.8351    0.8354      2837
weighted avg     0.8398    0.8400    0.8399      2837

Confusion Matrix:
[[1427  223]
 [ 231  956]]

######################################################################
SSL ROUND: 20pct_ssl_round1
######################################################################

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_20pct_ssl_round1
======================================================================
              precision    recall  f1-score   support

           0     0.8607    0.8648    0.8628      1650
           1     0.8109    0.8054    0.8081      1187

    accuracy                         0.8400      2837
   macro avg     0.8358    0.8351    0.8354      2837
weighted avg     0.8398    0.8400    0.8399      2837

Confusion Matrix:
[[1427  223]
 [ 231  956]]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: xlmr_20pct_ssl_round1
======================================================================
              precision    recall  f1-score   support

           0     0.8477    0.8636    0.8556      1650
           1     0.8054    0.7843    0.7947      1187

    accuracy                         0.8305      2837
   macro avg     0.8265    0.8240    0.8252      2837
weighted avg     0.8300    0.8305    0.8301      2837

Confusion Matrix:
[[1425  225]
 [ 256  931]]

Used pseudo-label threshold: 0.92
Pseudo-labeled added: 4084
Remaining unlabeled: 4086

######################################################################
SSL ROUND: 20pct_ssl_round2
######################################################################

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: indobert_20pct_ssl_round2
======================================================================
              precision    recall  f1-score   support

           0     0.8949    0.8461    0.8698      1650
           1     0.8011    0.8618    0.8304      1187

    accuracy                         0.8527      2837
   macro avg     0.8480    0.8539    0.8501      2837
weighted avg     0.8556    0.8527    0.8533      2837

Confusion Matrix:
[[1396  254]
 [ 164 1023]]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

======================================================================
RESULTS: xlmr_20pct_ssl_round2
======================================================================
              precision    recall  f1-score   support

           0     0.9024    0.8406    0.8704      1650
           1     0.7977    0.8736    0.8339      1187

    accuracy                         0.8544      2837
   macro avg     0.8500    0.8571    0.8522      2837
weighted avg     0.8586    0.8544    0.8552      2837

Confusion Matrix:
[[1387  263]
 [ 150 1037]]

Used pseudo-label threshold: 0.87
Pseudo-labeled added: 3881
Remaining unlabeled: 885

Top TEST results by macro-F1:
 label_fraction                     model  accuracy  macro_f1  macro_precision  macro_recall  roc_auc  best_threshold  seed
           0.20     xlmr_20pct_ssl_round2  0.854424  0.852174         0.850050      0.857119 0.924587            0.40    42
           0.20 indobert_20pct_ssl_round2  0.852661  0.850070         0.847984      0.853949 0.919821            0.38    42
           0.20            indobert_20pct  0.839972  0.835436         0.835766      0.835120 0.911851            0.24    42
           0.20 indobert_20pct_ssl_round1  0.839972  0.835436         0.835766      0.835120 0.911851            0.24    42
           0.10 indobert_10pct_ssl_round1  0.829397  0.825212         0.824402      0.826147 0.898199            0.76    42
           0.10            indobert_10pct  0.829397  0.825212         0.824402      0.826147 0.898199            0.76    42
           0.20     xlmr_20pct_ssl_round1  0.830455  0.825153         0.826537      0.823983 0.899392            0.64    42
           0.10 indobert_10pct_ssl_round2  0.827282  0.820963         0.824603      0.818419 0.897084            0.52    42
           0.10     xlmr_10pct_ssl_round2  0.823757  0.817557         0.820524      0.815389 0.883996            0.42    42
           0.10     xlmr_10pct_ssl_round1  0.809306  0.803589         0.804426      0.802846 0.874271            0.74    42
           0.05             indobert_5pct  0.805428  0.800198         0.800059      0.800341 0.882375            0.54    42
           0.05  indobert_5pct_ssl_round1  0.805428  0.800198         0.800059      0.800341 0.882375            0.54    42
           0.05  indobert_5pct_ssl_round2  0.803313  0.797690         0.798060      0.797340 0.882871            0.46    42
           0.05      xlmr_5pct_ssl_round2  0.792386  0.789711         0.788418      0.795157 0.860205            0.64    42
           0.05      xlmr_5pct_ssl_round1  0.767360  0.755967         0.764549      0.752129 0.821360            0.20    42